=== DraculaSOTD/AHI-Flutter-Body/ahi-bodyscan-react/downloaded/ahi-digitalhealthcheck-phil_conference/terraform-conference/unisure_bhalite_result_schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
        "session_id": {
            "type": "string",
            "description": "UUID generated identifier for the session."
        },
        "bool_ent_bpMedication": {
            "type": "string",
            "description": "Entry data indicating whether the user is currently taking blood pressure medication or not.",
            "enum": [
                "true",
                "false"
            ]
        },
        "cm_ent_height": {
            "type": "integer",
            "description": "Entry data indicating the user's height in centimeters.",
            "minimum": 100,
            "maximum": 250
        },
        "kg_ent_weight": {
            "type": "integer",
            "description": "Entry data indicating the user's reported weight in kilograms.",
            "minimum": 30,
            "maximum": 250
        },
        "date_ent_dob": {
            "type": "string",
            "description": "Entry data indicating the user's date of birth, formatted at YYYY-MM-DD."
        },
        "yr_raw_age": {
            "type": "integer",
            "description": "Entry data indicating the user's age in years, should date of birth not be provided."
        },
        "enum_ent_activityLevel": {
            "type": "string",
            "description": "Entry data indicating the user's speculated level of physical activity.",
            "enum": [
                "inactive",
                "exercise10Mins",
                "exercise20to60Mins",
                "exercise1to3Hours",
                "exerciseOver3Hours"
            ]
        },
        "enum_ent_chronicMedication": {
            "type": "string",
            "description": "Entry data indicating the user's medication intake for diseases.",
            "enum": [
                "none",
                "oneOrTwoDiseases",
                "threeOrMoreDiseases"
            ]
        },
        "enum_ent_sex": {
            "type": "string",
            "description": "Entry data indicating the user's biological sex.",
            "enum": [
                "male",
                "female"
            ]
        },
        "enum_ent_smoker": {
            "type": "string",
            "description": "Entry data indicating the user's smoking status.",
            "enum": [
                "never",
                "former",
                "current"
            ]
        },
        "email": {
            "type": "string",
            "description": "Entry data indicating the user's email if provided."
        },
        "bpm_ent_restingHeartRate": {
            "type": "string",
            "description": "Result value for resting heart-rate, in beats-per-minute (BPM)."
        },
        "created_at": {
            "type": "integer",
            "description": "Unix timestamp (seconds since Epoch 1/1/1970 GMT), when session started."
        },
        "flt_raw_ibi": {
            "type": "string"
        },
        "flt_raw_rmssd": {
            "type": "string"
        },
        "flt_raw_sdnn": {
            "type": "string"
        },
        "flt_raw_stressIndex": {
            "type": "string"
        },
        "int_raw_oxygen": {
            "type": "string",
            "description": "Result value for Oxygen Saturation levels (SpO2)."
        },
        "int_raw_rr": {
            "type": "string"
        },
        "mmHg_ent_diastolicBP": {
            "type": "string",
            "description": "Result value for Diastolic Blood Pressure (mmHg)."
        },
        "mmHg_ent_systolicBP": {
            "type": "string",
            "description": "Result value for Systolic Blood Pressure (mmHg)."
        },
        "questions_at": {
            "type": "integer",
            "description": "Unix timestamp (seconds since Epoch 1/1/1970 GMT), when questions all answered or provided."
        },
        "risk_adj_activityLevel": {
            "type": "string"

        },
        "risk_adj_bapwv": {
            "type": "string",
            "description": "Risk value for the Arterial pressure/stiffness.",
            "enum": [
                "low",
                "medium",
                "high"
            ]
        },
        "risk_adj_bloodPressure": {
            "type": "string",
            "description": "Risk value for the Blood Pressure.",
            "enum": [
                "low",
                "medium",
                "high"
            ]
        },
        "risk_adj_bmi": {
            "type": "string",
            "description": "Risk value for the Body Mass Index.",
            "enum": [
                "low",
                "medium",
                "high"
            ]
        },
        "risk_adj_chronicMedication": {
            "type": "string",
            "description": "Risk value for the use of medication for chronic diseases.",
            "enum": [
                "low",
                "medium",
                "high"
            ]
        },
        "risk_adj_framinghamScore": {
            "type": "string",
            "description": "Risk value for the Framingham Score.",
            "enum": [
                "low",
                "medium",
                "high"
            ]
        },
        "risk_adj_hdlC": {
            "type": "string",
            "description": "Risk value for HDL Cholesterol.",
            "enum": [
                "low",
                "medium",
                "high"
            ]
        },
        "risk_adj_ldlC": {
            "type": "string",
            "description": "Risk value for LDL Cholesterol.",
            "enum": [
                "low",
                "medium",
                "high"
            ]
        },
        "risk_adj_metSComp": {
            "type": "string",
            "description": "Risk value for Metabolic Syndrome.",
            "enum": [
                "low",
                "medium",
                "high"
            ]
        },
        "risk_adj_restingFitness": {
            "type": "string",
            "description": "Risk value for Resting Fitness Level.",
            "enum": [
                "low",
                "medium",
                "high"
            ]
        },
        "risk_adj_restingHeartRate": {
            "type": "string",
            "description": "Risk value for Resting Heart-Rate.",
            "enum": [
                "low",
                "medium",
                "high"
            ]
        },
        "risk_adj_smokerStatus": {
            "type": "string",
            "description": "Risk value for Smoker Status.",
            "enum": [
                "low",
                "medium",
                "high"
            ]
        },
        "risk_adj_tenYrCvd": {
            "type": "string",
            "description": "Risk value for 10-year Cardiovascular Syndrome.",
            "enum": [
                "low",
                "medium",
                "high"
            ]
        },
        "risk_adj_totalCholesterol": {
            "type": "string",
            "description": "Risk value for Total Cholesterol.",
            "enum": [
                "low",
                "medium",
                "high"
            ]
        },
        "risk_adj_triglycerides": {
            "type": "string",
            "description": "Risk value for Triglycerides.",
            "enum": [
                "low",
                "medium",
                "high"
            ]
        },
        "updated_at": {
            "type": "integer",
            "description": "Unix timestamp (seconds since Epoch 1/1/1970 GMT), when session was last updated."
        }
    },
    "anyOf":[
        {"required": ["date_ent_dob"]},
        {"required": ["yr_raw_age"]}
    ],
    "required": [
        "session_id",
        "bool_ent_bpMedication",
        "bpm_ent_restingHeartRate",
        "cm_ent_height",
        "enum_ent_activityLevel",
        "enum_ent_chronicMedication",
        "enum_ent_sex",
        "enum_ent_smoker",
        "kg_ent_weight",
        "created_at",
        "flt_raw_ibi",
        "flt_raw_rmssd",
        "flt_raw_sdnn",
        "flt_raw_stressIndex",
        "int_raw_oxygen",
        "int_raw_rr",
        "mmHg_ent_diastolicBP",
        "mmHg_ent_systolicBP",
        "questions_at",
        "risk_adj_activityLevel",
        "risk_adj_bapwv",
        "risk_adj_bloodPressure",
        "risk_adj_bmi",
        "risk_adj_chronicMedication",
        "risk_adj_framinghamScore",
        "risk_adj_hdlC",
        "risk_adj_ldlC",
        "risk_adj_metSComp",
        "risk_adj_restingFitness",
        "risk_adj_restingHeartRate",
        "risk_adj_smokerStatus",
        "risk_adj_tenYrCvd",
        "risk_adj_totalCholesterol",
        "risk_adj_triglycerides",
        "updated_at"
    ]
}

=== DraculaSOTD/AHI-Flutter-Body/ahi-bodyscan-react/downloaded/ahi-digitalhealthcheck-phil_conference/terraform-unisure/unisure_bhalite_result_example.json
{
    "session_id": "5646a0f4-f66b-418d-95ab-bf6127d1d695",
    "bool_ent_bpMedication": "true",
    "bpm_ent_restingHeartRate": "69",
    "cm_ent_height": 174,
    "date_ent_dob": "1986-05-06",
    "enum_ent_activityLevel": "exerciseOver3Hours",
    "enum_ent_chronicMedication": "oneOrTwoDiseases",
    "enum_ent_sex": "male",
    "enum_ent_smoker": "never",
    "kg_ent_weight": 73,
    "created_at": 1724652803,
    "email": "example@example.com",
    "flt_raw_ibi": "855.48",
    "flt_raw_rmssd": "50.83",
    "flt_raw_sdnn": "41.31",
    "flt_raw_stressIndex": "36.31049507791067",
    "int_raw_oxygen": "98",
    "int_raw_rr": "16",
    "mmHg_ent_diastolicBP": "82",
    "mmHg_ent_systolicBP": "118",
    "questions_at": 1724652830,
    "risk_adj_activityLevel": "low",
    "risk_adj_bapwv": "low",
    "risk_adj_bloodPressure": "medium",
    "risk_adj_bmi": "low",
    "risk_adj_chronicMedication": "medium",
    "risk_adj_framinghamScore": "low",
    "risk_adj_hdlC": "high",
    "risk_adj_ldlC": "medium",
    "risk_adj_metSComp": "low",
    "risk_adj_restingFitness": "low",
    "risk_adj_restingHeartRate": "low",
    "risk_adj_smokerStatus": "low",
    "risk_adj_tenYrCvd": "low",
    "risk_adj_totalCholesterol": "low",
    "risk_adj_triglycerides": "low",
    "updated_at": 1724652871,
    "yr_raw_age": 38
}
